/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nishan
 */
import java.awt.Color;
import java.awt.Desktop;
import java.awt.FileDialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.lang.System.Logger.Level;
import java.util.Arrays;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import static org.apache.commons.math3.fitting.leastsquares.LeastSquaresFactory.model;
import org.apache.log4j.Logger;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
public class SoftwareDesign extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form SoftwareDesign
     */
    public SoftwareDesign() {
        initComponents();
        bmw1.setVisible(false);
        bmw2.setVisible(false);
        bmw3.setVisible(false);
        bmw4.setVisible(false);

        tesla1.setVisible(false);
        tesla2.setVisible(false);
        tesla3.setVisible(false);
        tesla4.setVisible(false);  
        
        lambo1.setVisible(false);
        lambo2.setVisible(false);
        lambo3.setVisible(false);
        lambo4.setVisible(false);
          
        audi1.setVisible(false);
        audi2.setVisible(false);
        audi3.setVisible(false);
        audi4.setVisible(false); 
           
        tata1.setVisible(false);
        tata2.setVisible(false);
        tata3.setVisible(false);
        tata4.setVisible(false);
        
        
        
        //false properties
        propertiesPanel.setVisible(false);
        jTextField1.setVisible(false);
                jButton2.setVisible(false);
        
        
        //making condition
       
        
        
        
        
        
        
        
        
        
        
        
        
        
        // price of each car from all catagories seting value to false
      
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnBmw = new javax.swing.JButton();
        btnLambo = new javax.swing.JButton();
        btnTesla = new javax.swing.JButton();
        btnTata = new javax.swing.JButton();
        btnAudi = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tesla1 = new javax.swing.JButton();
        tata1 = new javax.swing.JButton();
        lambo1 = new javax.swing.JButton();
        audi1 = new javax.swing.JButton();
        bmw1 = new javax.swing.JButton();
        tata2 = new javax.swing.JButton();
        tesla2 = new javax.swing.JButton();
        lambo2 = new javax.swing.JButton();
        bmw2 = new javax.swing.JButton();
        lambo3 = new javax.swing.JButton();
        bmw3 = new javax.swing.JButton();
        bmw4 = new javax.swing.JButton();
        tesla3 = new javax.swing.JButton();
        audi3 = new javax.swing.JButton();
        tata3 = new javax.swing.JButton();
        lambo4 = new javax.swing.JButton();
        tesla4 = new javax.swing.JButton();
        audi4 = new javax.swing.JButton();
        tata4 = new javax.swing.JButton();
        audi2 = new javax.swing.JButton();
        headingText = new javax.swing.JLabel();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tataA3 = new javax.swing.JLabel();
        tataA6 = new javax.swing.JLabel();
        tataQ8 = new javax.swing.JLabel();
        tataQ7 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        a6 = new javax.swing.JLabel();
        q7 = new javax.swing.JLabel();
        q8 = new javax.swing.JLabel();
        urus = new javax.swing.JLabel();
        allendator = new javax.swing.JLabel();
        countach = new javax.swing.JLabel();
        hurican = new javax.swing.JLabel();
        semiTruck = new javax.swing.JLabel();
        cybertruck = new javax.swing.JLabel();
        y = new javax.swing.JLabel();
        s = new javax.swing.JLabel();
        x5 = new javax.swing.JLabel();
        m2 = new javax.swing.JLabel();
        i8 = new javax.swing.JLabel();
        pricex1 = new javax.swing.JLabel();
        propertiesPanel = new javax.swing.JPanel();
        companyName = new javax.swing.JLabel();
        companyLabel = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        red = new javax.swing.JRadioButton();
        black = new javax.swing.JRadioButton();
        grey = new javax.swing.JRadioButton();
        color = new javax.swing.JLabel();
        reviewLabel = new javax.swing.JLabel();
        displayPrice = new javax.swing.JLabel();
        modelNumber = new javax.swing.JLabel();
        ModelLabel = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        selectFuel = new javax.swing.JComboBox<>();
        fuelType1 = new javax.swing.JLabel();
        yourMessage = new javax.swing.JTextField();
        errorMsg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setText("Enter Price of Vechicles  Range[9000000 - 125000000]");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 470, 40));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBmw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/btn/3.png"))); // NOI18N
        btnBmw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBmwActionPerformed(evt);
            }
        });
        jPanel1.add(btnBmw, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, 217, 56));

        btnLambo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/btn/5.png"))); // NOI18N
        btnLambo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamboActionPerformed(evt);
            }
        });
        jPanel1.add(btnLambo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 217, 56));

        btnTesla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/btn/4.png"))); // NOI18N
        btnTesla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeslaActionPerformed(evt);
            }
        });
        jPanel1.add(btnTesla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 186, 217, 56));

        btnTata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/btn/7.png"))); // NOI18N
        btnTata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTataActionPerformed(evt);
            }
        });
        jPanel1.add(btnTata, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 403, 217, 56));

        btnAudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/btn/6.png"))); // NOI18N
        btnAudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAudiActionPerformed(evt);
            }
        });
        jPanel1.add(btnAudi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 332, 218, 56));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/btn/sdf.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, 217, 51));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 480));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/btn/seasrch.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 140, 40));

        tesla1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/tesla/crop modelS.jpg"))); // NOI18N
        tesla1.setText("jButton6");
        tesla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tesla1ActionPerformed(evt);
            }
        });
        getContentPane().add(tesla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 160, 120));

        tata1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/tata/2.jpg"))); // NOI18N
        tata1.setText("jButton6");
        tata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tata1ActionPerformed(evt);
            }
        });
        getContentPane().add(tata1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 160, 120));

        lambo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/lambo/hurican.jpg"))); // NOI18N
        lambo1.setText("jButton6");
        lambo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lambo1ActionPerformed(evt);
            }
        });
        getContentPane().add(lambo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 160, 120));

        audi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/audi/crop/1.jpg"))); // NOI18N
        audi1.setText("jButton6");
        audi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audi1ActionPerformed(evt);
            }
        });
        getContentPane().add(audi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 160, 120));

        bmw1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/crop x1.jpg"))); // NOI18N
        bmw1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmw1ActionPerformed(evt);
            }
        });
        getContentPane().add(bmw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 170, 120));

        tata2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/tata/1.jpg"))); // NOI18N
        tata2.setText("jButton6");
        tata2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tata2ActionPerformed(evt);
            }
        });
        getContentPane().add(tata2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 160, -1));

        tesla2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/tesla/cropY.jpg"))); // NOI18N
        tesla2.setText("jButton6");
        tesla2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tesla2ActionPerformed(evt);
            }
        });
        getContentPane().add(tesla2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, 163, 120));

        lambo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/lambo/4th car crop.jpg"))); // NOI18N
        lambo2.setText("jButton6");
        lambo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lambo2ActionPerformed(evt);
            }
        });
        getContentPane().add(lambo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, 163, 120));

        bmw2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/i8 crop.jpg"))); // NOI18N
        bmw2.setText("jButton6");
        bmw2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmw2ActionPerformed(evt);
            }
        });
        getContentPane().add(bmw2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, 160, 120));

        lambo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/lambo/lambo-1 crop.jpg"))); // NOI18N
        lambo3.setText("jButton6");
        lambo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lambo3ActionPerformed(evt);
            }
        });
        getContentPane().add(lambo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 160, 120));

        bmw3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/m2.jpg"))); // NOI18N
        bmw3.setText("jButton6");
        bmw3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmw3ActionPerformed(evt);
            }
        });
        getContentPane().add(bmw3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 163, 137));

        bmw4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/x5 crop.jpg"))); // NOI18N
        bmw4.setText("jButton6");
        bmw4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmw4ActionPerformed(evt);
            }
        });
        getContentPane().add(bmw4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, 163, 120));

        tesla3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/tesla/cyberCrop.jpg"))); // NOI18N
        tesla3.setText("jButton6");
        tesla3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tesla3ActionPerformed(evt);
            }
        });
        getContentPane().add(tesla3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 163, 120));

        audi3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/audi/crop/4.jpg"))); // NOI18N
        audi3.setText("jButton6");
        audi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audi3ActionPerformed(evt);
            }
        });
        getContentPane().add(audi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 163, 137));

        tata3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/tata/3.jpg"))); // NOI18N
        tata3.setText("jButton6");
        tata3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tata3ActionPerformed(evt);
            }
        });
        getContentPane().add(tata3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 163, 137));

        lambo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/lambo/urus-crop.jpg"))); // NOI18N
        lambo4.setText("jButton6");
        lambo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lambo4ActionPerformed(evt);
            }
        });
        getContentPane().add(lambo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 160, 120));

        tesla4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/tesla/cropTruckCrop.jpg"))); // NOI18N
        tesla4.setText("jButton6");
        tesla4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tesla4ActionPerformed(evt);
            }
        });
        getContentPane().add(tesla4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 150, 120));

        audi4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/audi/crop/dsjfh.jpg"))); // NOI18N
        audi4.setText("jButton6");
        audi4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audi4ActionPerformed(evt);
            }
        });
        getContentPane().add(audi4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 160, 120));

        tata4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/tata/4.jpg"))); // NOI18N
        tata4.setText("jButton6");
        tata4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tata4ActionPerformed(evt);
            }
        });
        getContentPane().add(tata4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, 160, 120));

        audi2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/audi/crop/3.jpg"))); // NOI18N
        audi2.setText("jButton6");
        audi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audi2ActionPerformed(evt);
            }
        });
        getContentPane().add(audi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, 160, 120));

        headingText.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        headingText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/h2.png"))); // NOI18N
        getContentPane().add(headingText, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 770, 60));

        tablePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Company Name", "Model No", "Color", "Fuel Type", "Price", "Review"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        tablePanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1010, 190));

        tataA3.setText("10100000");
        tablePanel.add(tataA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, -1, -1));

        tataA6.setText("15000000");
        tablePanel.add(tataA6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, -1, -1));

        tataQ8.setText("65000020");
        tablePanel.add(tataQ8, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 90, -1, -1));

        tataQ7.setText("34000000");
        tablePanel.add(tataQ7, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 70, -1, -1));

        a3.setText("10000000");
        tablePanel.add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 60, -1, -1));

        a6.setText("12000000");
        tablePanel.add(a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 40, -1, -1));

        q7.setText("34000030");
        tablePanel.add(q7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 60, -1, -1));

        q8.setText("65000060");
        tablePanel.add(q8, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 90, -1, -1));

        urus.setText("90002000");
        tablePanel.add(urus, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 120, -1, -1));

        allendator.setText("190000000");
        tablePanel.add(allendator, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, -1, -1));

        countach.setText("65000000");
        tablePanel.add(countach, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, -1, -1));

        hurican.setText("125000000");
        tablePanel.add(hurican, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 100, -1, -1));

        semiTruck.setText("100000000");
        tablePanel.add(semiTruck, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 80, 60, 20));

        cybertruck.setText("9000000");
        tablePanel.add(cybertruck, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 80, 60, 20));

        y.setText("50000000");
        tablePanel.add(y, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 80, 60, 20));

        s.setText("30000010");
        tablePanel.add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 80, 60, 20));

        x5.setText("32000000");
        tablePanel.add(x5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 80, 60, 20));

        m2.setText("30000000");
        tablePanel.add(m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 70, 60, 20));

        i8.setText("60000000");
        tablePanel.add(i8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 60, 60, 20));

        pricex1.setText("12000000");
        tablePanel.add(pricex1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 80, 60, 20));

        getContentPane().add(tablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 1090, 210));

        propertiesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        companyName.setText("Bmw");
        propertiesPanel.add(companyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 71, 36));

        companyLabel.setText("Company Name:");
        propertiesPanel.add(companyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 36));

        price.setText("Price");
        propertiesPanel.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 71, 36));

        buttonGroup1.add(red);
        red.setText("Red");
        red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redActionPerformed(evt);
            }
        });
        propertiesPanel.add(red, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        buttonGroup1.add(black);
        black.setText("Black");
        propertiesPanel.add(black, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        buttonGroup1.add(grey);
        grey.setText("Grey");
        propertiesPanel.add(grey, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        color.setText("Colors");
        propertiesPanel.add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 71, 36));

        reviewLabel.setText("Review:");
        propertiesPanel.add(reviewLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 71, 36));

        displayPrice.setText("RS:-  Aaukat chaina tero");
        propertiesPanel.add(displayPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 145, 36));

        modelNumber.setText("Model No:");
        propertiesPanel.add(modelNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 71, 36));

        ModelLabel.setText("Model No:");
        propertiesPanel.add(ModelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 71, 36));

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/btn/clear.png"))); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        propertiesPanel.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 120, 40));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/bmw/btn/btnsave.jpg"))); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        propertiesPanel.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 120, 40));

        selectFuel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Petrol", "Desel", "Electric" }));
        selectFuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFuelActionPerformed(evt);
            }
        });
        propertiesPanel.add(selectFuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 110, 20));

        fuelType1.setText("Fuel Type");
        propertiesPanel.add(fuelType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 71, 36));
        propertiesPanel.add(yourMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 200, 70));

        errorMsg.setForeground(new java.awt.Color(255, 0, 0));
        propertiesPanel.add(errorMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 170, 20));

        getContentPane().add(propertiesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 340, 400));

        jMenu1.setText("File");
        jMenu1.add(jSeparator1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem3.setText("How To Use");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);
        jMenu2.add(jSeparator3);
        jMenu2.add(jSeparator4);

        jMenuItem4.setText("About Us");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBmwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBmwActionPerformed
        // TODO add your handling code here:
        bmw1.setVisible(true);
        bmw2.setVisible(true);
        bmw3.setVisible(true);
        bmw4.setVisible(true);
        
        //  false values
        tesla1.setVisible(false);
         tesla2.setVisible(false);
          tesla3.setVisible(false);
           tesla4.setVisible(false);
           
        //lambo 
        lambo1.setVisible(false);
        lambo2.setVisible(false);
        lambo3.setVisible(false);
        lambo4.setVisible(false);
        
        
        //audi
        audi1.setVisible(false);
         audi2.setVisible(false);
          audi3.setVisible(false);
           audi4.setVisible(false);
           
        
         // tata 
           
        tata1.setVisible(false);
        tata2.setVisible(false);
        tata3.setVisible(false);
        tata4.setVisible(false);
        
        // properties panel false
        propertiesPanel.setVisible(false);
        
        
        jTextField1.setVisible(false);
                jButton2.setVisible(false);
                                            
        
        
         // error message remove
        errorMsg.setText("");
        
    }//GEN-LAST:event_btnBmwActionPerformed

    private void lambo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lambo1ActionPerformed
        // TODO add your handling code here:
        lambo1.setVisible(true);
        lambo2.setVisible(false);
        lambo3.setVisible(false);
        lambo4.setVisible(false);
        
        //properties panel on 
        propertiesPanel.setVisible(true);
        
        // properties values
        
        companyName.setText("Lamborgini");
        modelNumber.setText("Huracan");
        selectFuel.setSelectedIndex(0);
        displayPrice.setText("RS 125000000");

        
    }//GEN-LAST:event_lambo1ActionPerformed

    private void lambo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lambo3ActionPerformed
        // TODO add your handling code here:
        lambo1.setVisible(false);
        lambo2.setVisible(false);
        lambo3.setVisible(true);
        lambo4.setVisible(false);
        
        //properties panel on 
        propertiesPanel.setVisible(true);
        
        // propoerties values
        
        companyName.setText("Lamborgini");
        modelNumber.setText("Avendator");
        selectFuel.setSelectedIndex(0);
        displayPrice.setText("RS 190000000");

        
    }//GEN-LAST:event_lambo3ActionPerformed

    private void lambo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lambo4ActionPerformed
        // TODO add your handling code here:
        lambo1.setVisible(false);
        lambo2.setVisible(false);
        lambo3.setVisible(false);
        lambo4.setVisible(true);
        
        //properties panel on 
        propertiesPanel.setVisible(true);
        
        // properties values
       
        companyName.setText("Lamborgini");
        modelNumber.setText("Urus");
        selectFuel.setSelectedIndex(0);
        displayPrice.setText("RS 90002000");

    }//GEN-LAST:event_lambo4ActionPerformed

    private void btnTeslaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeslaActionPerformed
        // TODO add your handling code here:
        
        // true for tesla only
        tesla1.setVisible(true);
        tesla2.setVisible(true);
        tesla3.setVisible(true);
        tesla4.setVisible(true); 
        
        
        //false for other remaining 
        bmw1.setVisible(false);
        bmw2.setVisible(false);
        bmw3.setVisible(false);
        bmw4.setVisible(false);
        
         lambo1.setVisible(false);
        lambo2.setVisible(false);
        lambo3.setVisible(false);
        lambo4.setVisible(false);
          
        audi1.setVisible(false);
        audi2.setVisible(false);
        audi3.setVisible(false);
        audi4.setVisible(false); 
           
        tata1.setVisible(false);
        tata2.setVisible(false);
        tata3.setVisible(false);
        tata4.setVisible(false);
        
        // properties panel false
        propertiesPanel.setVisible(false);
        
        jTextField1.setVisible(false);
                jButton2.setVisible(false);
        
         // error message remove
        errorMsg.setText("");
        
        
    }//GEN-LAST:event_btnTeslaActionPerformed

    private void btnLamboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamboActionPerformed
        // TODO add your handling code here:
        lambo1.setVisible(true);
        lambo2.setVisible(true);
        lambo3.setVisible(true);
        lambo4.setVisible(true);
        
        
        // other false
        bmw1.setVisible(false);
        bmw2.setVisible(false);
        bmw3.setVisible(false);
        bmw4.setVisible(false);

        tesla1.setVisible(false);
        tesla2.setVisible(false);
        tesla3.setVisible(false);
        tesla4.setVisible(false);  
        
        audi1.setVisible(false);
        audi2.setVisible(false);
        audi3.setVisible(false);
        audi4.setVisible(false); 
           
        tata1.setVisible(false);
        tata2.setVisible(false);
        tata3.setVisible(false);
        tata4.setVisible(false);
        
        //properties panel false
        propertiesPanel.setVisible(false);
        
        jTextField1.setVisible(false);
                jButton2.setVisible(false);
        
         // error message remove
        errorMsg.setText("");
        
    }//GEN-LAST:event_btnLamboActionPerformed

    private void btnAudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAudiActionPerformed
        // TODO add your handling code here:
        audi1.setVisible(true);
        audi2.setVisible(true);
        audi3.setVisible(true);
        audi4.setVisible(true); 
        
        // remaining false
        bmw1.setVisible(false);
        bmw2.setVisible(false);
        bmw3.setVisible(false);
        bmw4.setVisible(false);

        tesla1.setVisible(false);
        tesla2.setVisible(false);
        tesla3.setVisible(false);
        tesla4.setVisible(false);  
        
        lambo1.setVisible(false);
        lambo2.setVisible(false);
        lambo3.setVisible(false);
        lambo4.setVisible(false);
        
        tata1.setVisible(false);
        tata2.setVisible(false);
        tata3.setVisible(false);
        tata4.setVisible(false);
        
        //properties panel false 
        propertiesPanel.setVisible(false);
        
        jTextField1.setVisible(false);
                jButton2.setVisible(false);
        
         // error message remove
        errorMsg.setText("");
        
        
    }//GEN-LAST:event_btnAudiActionPerformed

    private void btnTataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTataActionPerformed
        // TODO add your handling code here:
        tata1.setVisible(true);
        tata2.setVisible(true);
        tata3.setVisible(true);
        tata4.setVisible(true);
        
        bmw1.setVisible(false);
        bmw2.setVisible(false);
        bmw3.setVisible(false);
        bmw4.setVisible(false);

        tesla1.setVisible(false);
        tesla2.setVisible(false);
        tesla3.setVisible(false);
        tesla4.setVisible(false);  
        
        lambo1.setVisible(false);
        lambo2.setVisible(false);
        lambo3.setVisible(false);
        lambo4.setVisible(false);
          
        audi1.setVisible(false);
        audi2.setVisible(false);
        audi3.setVisible(false);
        audi4.setVisible(false); 
        
        //properties panel false
        propertiesPanel.setVisible(false);
        
        jTextField1.setVisible(false);
                jButton2.setVisible(false);
        
        
         // error message remove
        errorMsg.setText("");
        
    }//GEN-LAST:event_btnTataActionPerformed

    private void bmw1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmw1ActionPerformed
        // TODO add your handling code here:
        bmw1.setVisible(true);
        bmw2.setVisible(false);
        bmw3.setVisible(false);
        bmw4.setVisible(false);
        
        //properties panel on 
        propertiesPanel.setVisible(true);
        
        // properties values
        companyName.setText("BMW");
        modelNumber.setText("X1");
        selectFuel.setSelectedIndex(0);
        displayPrice.setText("RS 12000000");
        
        
        // error message remove
        errorMsg.setText("");
        
        
       
        
    }//GEN-LAST:event_bmw1ActionPerformed

    private void redActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redActionPerformed

    private void bmw2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmw2ActionPerformed
        // TODO add your handling code here:
        
            companyName.setText("BMW ");
            modelNumber.setText("i8");
            selectFuel.setSelectedIndex(0);
            displayPrice.setText("RS 60000000");

        
        
        
        bmw1.setVisible(false);
        bmw2.setVisible(true);
        bmw3.setVisible(false);
        bmw4.setVisible(false);
        
        //properties panel on 
        propertiesPanel.setVisible(true);
        
        companyName.setText("BMW");
        
      
        
        
        //panelShow.add(lambo2);
     // panelShow.repaint(lambo2);
       //panelShow.revalidate();
       
        // error message remove
        errorMsg.setText("");
    }//GEN-LAST:event_bmw2ActionPerformed

    private void bmw3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmw3ActionPerformed
        // TODO add your handling code here:
         bmw1.setVisible(false);
        bmw2.setVisible(false);
        bmw3.setVisible(true);
        bmw4.setVisible(false);
        
        //properties panel on 
        propertiesPanel.setVisible(true);
        
        
        
        companyName.setText("BMW");
        modelNumber.setText("M2");
        selectFuel.setSelectedIndex(0);
        displayPrice.setText("RS 30000000");
        
         // error message remove
        errorMsg.setText("");

    }//GEN-LAST:event_bmw3ActionPerformed

    private void bmw4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmw4ActionPerformed
        // TODO add your handling code here:
        
         bmw1.setVisible(false);
        bmw2.setVisible(false);
        bmw3.setVisible(false);
        bmw4.setVisible(true);
        
        //properties panel on 
        propertiesPanel.setVisible(true);
        
        
        // Properties Values
        
        companyName.setText("BMW");
        modelNumber.setText("X5");
        selectFuel.setSelectedIndex(0);
        displayPrice.setText("RS 32000000");
        
         // error message remove
        errorMsg.setText("");

    }//GEN-LAST:event_bmw4ActionPerformed

    private void tesla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tesla1ActionPerformed
        // TODO add your handling code here:
        tesla1.setVisible(true);
        tesla2.setVisible(false);
        tesla3.setVisible(false);
        tesla4.setVisible(false);
        
        //properties panel on 
        propertiesPanel.setVisible(true);
        
        
        // properties values
        
        companyName.setText("TESLA");
        modelNumber.setText("Model S");
        selectFuel.setSelectedIndex(0);
        displayPrice.setText("RS 30000010");
        
         // error message remove
        errorMsg.setText("");

        
        
        
        
    }//GEN-LAST:event_tesla1ActionPerformed

    private void tesla2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tesla2ActionPerformed
        // TODO add your handling code here:
        tesla1.setVisible(false);
        tesla2.setVisible(true);
        tesla3.setVisible(false);
        tesla4.setVisible(false);
        
        //properties panel on 
        propertiesPanel.setVisible(true);
        
        // tesla properties
        
        companyName.setText("Tesla");
        modelNumber.setText("Model Y");
        selectFuel.setSelectedIndex(0);
        displayPrice.setText("RS 50000000");
        
        
         // error message remove
        errorMsg.setText("");

    }//GEN-LAST:event_tesla2ActionPerformed

    private void tesla3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tesla3ActionPerformed
        // TODO add your handling code here:
        tesla1.setVisible(false);
        tesla2.setVisible(false);
        tesla3.setVisible(true);
        tesla4.setVisible(false);
        
        //properties panel on 
        propertiesPanel.setVisible(true);
        
        
        companyName.setText("Tesla");
        modelNumber.setText("Cyber Truck");
        selectFuel.setSelectedIndex(0);
        displayPrice.setText("RS 9000000");
        
        
         // error message remove
        errorMsg.setText("");
    }//GEN-LAST:event_tesla3ActionPerformed

    private void tesla4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tesla4ActionPerformed
        // TODO add your handling code here:
        tesla1.setVisible(false);
        tesla2.setVisible(false);
        tesla3.setVisible(false);
        tesla4.setVisible(true);
        
        //properties panel on 
        propertiesPanel.setVisible(true);
        
        companyName.setText("Tesla");
        modelNumber.setText("Semi Truck");
        selectFuel.setSelectedIndex(0);
        displayPrice.setText("RS 100000000");
    }//GEN-LAST:event_tesla4ActionPerformed

    private void lambo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lambo2ActionPerformed
        // TODO add your handling code here:
        lambo1.setVisible(false);
        lambo2.setVisible(true);
        lambo3.setVisible(false);
        lambo4.setVisible(false);
        
        //properties panel on 
        propertiesPanel.setVisible(true);
        
        // properties values
        
        companyName.setText("Lamborgini");
        modelNumber.setText("countach");
        selectFuel.setSelectedIndex(0);
        displayPrice.setText("RS 65000000");

        
    }//GEN-LAST:event_lambo2ActionPerformed

    private void audi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audi1ActionPerformed
        // TODO add your handling code here:
        audi1.setVisible(true);
        audi2.setVisible(false);
        audi3.setVisible(false);
        audi4.setVisible(false);
        
        //properties panel on 
        propertiesPanel.setVisible(true);
        
        //properties values
        
            companyName.setText("Audi");
            modelNumber.setText("Q8");
            selectFuel.setSelectedIndex(0);
            displayPrice.setText("RS 65000060");

    }//GEN-LAST:event_audi1ActionPerformed

    private void audi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audi2ActionPerformed
        // TODO add your handling code here:
        audi1.setVisible(false);
        audi2.setVisible(true);
        audi3.setVisible(false);
        audi4.setVisible(false);
        
        //properties panel on 
        propertiesPanel.setVisible(true);
        
        // properties values
        
        companyName.setText("Audi");
        modelNumber.setText("Q7");
        selectFuel.setSelectedIndex(0);
        displayPrice.setText("RS 34000030");

        
    }//GEN-LAST:event_audi2ActionPerformed

    private void audi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audi3ActionPerformed
        // TODO add your handling code here:
        audi1.setVisible(false);
        audi2.setVisible(false);
        audi3.setVisible(true);
        audi4.setVisible(false);
        
        
        //properties panel on 
        propertiesPanel.setVisible(true);
        
        
        // properties values
        companyName.setText("BMW");
        modelNumber.setText("A6");
        selectFuel.setSelectedIndex(2);
        displayPrice.setText("RS 12000000");

    }//GEN-LAST:event_audi3ActionPerformed

    private void audi4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audi4ActionPerformed
        // TODO add your handling code here:
        audi1.setVisible(false);
        audi2.setVisible(false);
        audi3.setVisible(false);
        audi4.setVisible(true);
        
        
        //properties panel on 
        propertiesPanel.setVisible(true);
        
        
        
        companyName.setText("Audi");
        modelNumber.setText("A3");
        selectFuel.setSelectedIndex(2);
        displayPrice.setText("RS 10000000");
    }//GEN-LAST:event_audi4ActionPerformed

    private void tata1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tata1ActionPerformed
        // TODO add your handling code here:
        tata1.setVisible(true);
        tata2.setVisible(false);
        tata3.setVisible(false);
        tata4.setVisible(false);
        
        //properties panel on 
        propertiesPanel.setVisible(true);
        
        
        // tata car values
        companyName.setText("Tata");
        modelNumber.setText("Q7");
        selectFuel.setSelectedIndex(2);
        displayPrice.setText("RS 34000000");
        
    }//GEN-LAST:event_tata1ActionPerformed

    private void tata2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tata2ActionPerformed
        // TODO add your handling code here:
        tata1.setVisible(false);
        tata2.setVisible(true);
        tata3.setVisible(false);
        tata4.setVisible(false);
        
        //properties panel on 
        propertiesPanel.setVisible(true);
        
        
        // tata car values for second car
        companyName.setText("Tata");
        modelNumber.setText("Q8");
        selectFuel.setSelectedIndex(2);
        displayPrice.setText("RS 65000020");
    }//GEN-LAST:event_tata2ActionPerformed

    private void tata3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tata3ActionPerformed
        // TODO add your handling code here:
        tata1.setVisible(false);
        tata2.setVisible(false);
        tata3.setVisible(true);
        tata4.setVisible(false);
        
        //properties panel on 
        propertiesPanel.setVisible(true);
        
        // tata car values for third  car
        companyName.setText("Tata");
        modelNumber.setText("A6");
        selectFuel.setSelectedIndex(2);
        displayPrice.setText("RS 15000000");
    }//GEN-LAST:event_tata3ActionPerformed

    private void tata4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tata4ActionPerformed
        // TODO add your handling code here:
        tata1.setVisible(false);
        tata2.setVisible(false);
        tata3.setVisible(false);
        tata4.setVisible(true);
        
        //properties panel on 
        propertiesPanel.setVisible(true);
        
        
         // tata car values for third  car
        companyName.setText("Tata");
        modelNumber.setText("A3");
        selectFuel.setSelectedIndex(2);
        displayPrice.setText("RS 15000000");
    }//GEN-LAST:event_tata4ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        buttonGroup1.clearSelection();
        selectFuel.setSelectedIndex(0);
        yourMessage.setText("");
        
        
        // hide error message when clear button is clicked
        errorMsg.setText("");
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        String storeName= companyName.getText(); // company name of a car 
        String storeModel=modelNumber.getText(); // model number of car  
        String storePrice=displayPrice.getText(); // price of a car
        String storeReview=yourMessage.getText(); // review message of a car
        
        // for radio buttons
        String selection=null;
        
        if(red.isSelected()){
            selection="Red";
         }
        if(black.isSelected()){
            selection="Black";
        }
        if(grey.isSelected()){
            selection="Grey";
        }
       
         //combobox action performed
        String selectedItem=(String)selectFuel.getSelectedItem(); //comboBox value

       
        
        // checking weather text and components are empty or not
         
         
             
            
             int pointRow=0; // to point ROW
        
             String getValue;
        
            int rowCount=jTable1.getRowCount();
            int columnCount=jTable1.getColumnCount();
            boolean isEmpty=false;
            
            
            // Validation 
            if(red.isSelected()==true || black.isSelected()==true || grey.isSelected()==true){
             //errorMsg.setText("*Fields Cannot be empty");
             
                    
                    if(selectFuel.getSelectedIndex()!=0){
                        
                        if(!storeReview.isEmpty()){
                        
                        
                         String valuesDatas[]={storeName,storeModel,selection,selectedItem,storePrice,storeReview};
                         
                        
                

            do{

                getValue=(String)jTable1.getValueAt(pointRow,0); // convertng object into string to store values in a table
                if(getValue!=null && getValue.length()!=0){
                pointRow++;
              }
                else{
                    isEmpty=true;
                }
            }
                while(pointRow<rowCount && !isEmpty);

                for(int i=0;i<columnCount;i++){
                    jTable1.setValueAt(valuesDatas[i], pointRow, i);
                    
                    // after adding values in table error message should be clear
                    errorMsg.setText("");
                    

                }
                
                    }
                    
                    else{
                    
                       
                         JOptionPane.showMessageDialog(this,"Give Your Review" +
"                        "); 
                        
                    }
                }
                
                else{
                    
                    JOptionPane.showMessageDialog(this," Select Fuel Type"); 
                }
                
            }
            
            else{
               // errorMsg.setText("* Select Color" );
                JOptionPane.showMessageDialog(this,"Select Color of the Car ");
            }
      
         
       
        
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void selectFuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFuelActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_selectFuelActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        

       
    
        
        
        
        
        
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    
    
    
       
       
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        
        
        bmw1.setVisible(false);
        bmw2.setVisible(false);
        bmw3.setVisible(false);
        bmw4.setVisible(false);
        
        
        
        
        pricex1.setVisible(false);
        int Pricex1=Integer .parseInt(pricex1.getText());
        
        i8.setVisible(false);
        int I8=Integer .parseInt(i8.getText());
        
        m2.setVisible(false);
        int M2=Integer .parseInt(m2.getText());
        
        x5.setVisible(false);
        int X5=Integer .parseInt(x5.getText());
        
      
        
        s.setVisible(false);
        int S=Integer .parseInt(s.getText());
        
        y.setVisible(false);
        int Y=Integer .parseInt(y.getText());
        
        cybertruck.setVisible(false);
        int Cybertruck=Integer .parseInt(cybertruck.getText());
        
        semiTruck.setVisible(false);
        int SemiTruck=Integer .parseInt(semiTruck.getText());
        
        
        
        hurican.setVisible(false);
        int Hurican=Integer .parseInt(hurican.getText());
        
        countach.setVisible(false);
        int Countach=Integer .parseInt(countach.getText());
        
        allendator.setVisible(false);
        int Allendator=Integer .parseInt(allendator.getText());
        
        urus.setVisible(false);
        int Urus=Integer .parseInt(urus.getText());
        
        
        
        
        q8.setVisible(false);
        int Q8=Integer .parseInt(q8.getText());
        
        q7.setVisible(false);
        int Q7=Integer .parseInt(q7.getText());
        
        a6.setVisible(false);
        int A6=Integer .parseInt(a6.getText());
        
        a3.setVisible(false);
        int A3=Integer .parseInt(a3.getText());
        
        
        
        tataQ7.setVisible(false);
        int TataQ7=Integer .parseInt(tataQ7.getText());
        
        tataQ8.setVisible(false);
        int TataQ8=Integer .parseInt(tataQ8.getText());
        
        tataA6.setVisible(false);
        int TataA6=Integer .parseInt(tataA6.getText());
       
        tataA3.setVisible(false);
        int TataA3=Integer .parseInt(tataA3.getText());
        
      
      
      
      
      
      
      int dataBase[]={Pricex1,I8,M2,X5,S,Y,Cybertruck,SemiTruck,Hurican,Countach,Allendator,Urus,Q8, Q7, A6, A3, TataQ7, TataQ8, TataA6, TataA3};
      
      
      
            
       int resultSort[];
      resultSort=sort(dataBase);
      // getting value of user textfield
      
      try{
            if(jTextField1.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Text Field Cannot left Empty");
                
            }
            
            
            else{
                String userData=jTextField1.getText();
                 int userInput=Integer.parseInt(userData);
                  binarySearch(resultSort,userInput);
            
            }
      }catch (Exception ex) {
               JOptionPane.showMessageDialog(null,"Invalid Entry");
            }
          
      
           
                
           
      
      
      
      
      
      
    
      
     
      
      //passing array to binary search
     
 
  

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextField1.setVisible(true);
                jButton2.setVisible(true);
                
                bmw1.setVisible(false);
        bmw2.setVisible(false);
        bmw3.setVisible(false);
        bmw4.setVisible(false);

        tesla1.setVisible(false);
        tesla2.setVisible(false);
        tesla3.setVisible(false);
        tesla4.setVisible(false);  
        
        lambo1.setVisible(false);
        lambo2.setVisible(false);
        lambo3.setVisible(false);
        lambo4.setVisible(false);
          
        audi1.setVisible(false);
        audi2.setVisible(false);
        audi3.setVisible(false);
        audi4.setVisible(false); 
           
        tata1.setVisible(false);
        tata2.setVisible(false);
        tata3.setVisible(false);
        tata4.setVisible(false);
        propertiesPanel.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
        if(jTextField1.getText().equals("Enter Price of Vechicles  Range[9000000 - 125000000]")){
            jTextField1.setText("");
            
            
        }
        
        
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        
        if(jTextField1.getText().equals("Enter Price of Vechicles  Range[9000000 - 125000000]")){
            jTextField1.setText("");
          
            
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        try{
            File file = new File("src/coursework/manual.pdf");
            if(file.exists()){
                if(Desktop.isDesktopSupported()){
                    
                    Desktop.getDesktop().open(file);
                }
                else{
                     JOptionPane.showMessageDialog(this,"Not Suported");
                }
                   
                }
            
                else{
                    JOptionPane.showMessageDialog(this,"File Not Exist ");
                }
            }
            catch(Exception e){
                        e.printStackTrace();
                    }
        
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        try{
            File file = new File("src/coursework/teams.pdf");
            if(file.exists()){
                if(Desktop.isDesktopSupported()){
                    
                    Desktop.getDesktop().open(file);
                }
                else{
                     JOptionPane.showMessageDialog(this,"Not Suported");
                }
                   
                }
            
                else{
                    JOptionPane.showMessageDialog(this,"File Not Exist ");
                }
            }
            catch(Exception e){
                        e.printStackTrace();
                    }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    
    public static int[] sort(int a[]){
        int min,temp=0;
        for(int i=0;i<a.length;i++){
            min=i;
            for(int j=i+1;j<a.length;j++){
                if(a[j]< a[min]){
                    min=j;
                }
            }
            temp=a[i];
            a[i]=a[min];
            a[min]=temp;
        }
        for(int i=0;i<a.length;i++){
        
        }
        
        return a;
      
    }
    
  

    public void binarySearch(int b[],int toFind){
        int search=toFind;
        int lowerIndex=0;
        int higherIndex=b.length-1;
        int midIndex=(lowerIndex + higherIndex) / 2;
        
        while(lowerIndex <= higherIndex){
        
            if(b[midIndex]==search){
            
                System.out.println("\n found at index"+b[midIndex]);
                
                
                if(b[midIndex]==12000000){
                    JOptionPane.showMessageDialog(null,"<html>Name: Bmw X1<br>Price: RS 12000000</html>");
                      break;
                }  
                
                
                
                if(b[midIndex]==60000000){
                    JOptionPane.showMessageDialog(null,"<html>Name: Bmw i8<br>Price: RS 60000000</html>");
                      break;
                }  
                
                if(b[midIndex]==30000000){
                    JOptionPane.showMessageDialog(null,"<html>Name: Bmw M2<br>Price: RS 30000000</html>");
                      break;
                }  
                
                
                if(b[midIndex]==32000000){
                    JOptionPane.showMessageDialog(null,"<html>Name: Bmw X5<br>Price: RS 32000000</html>");
                      break;
                }  
                
                
                // tesla car
                
                if(b[midIndex]==30000010){
                    JOptionPane.showMessageDialog(null,"<html>Name: Tesla Model S<br>Price: RS 30000010</html>");
                      break;
                }
                
                
                if(b[midIndex]==50000000){
                    JOptionPane.showMessageDialog(null,"<html>Name: Tesla Model Y<br>Price: RS 50000000</html>");
                      break;
                }
                
                if(b[midIndex]==9000000){
                    JOptionPane.showMessageDialog(null,"<html>Name: Tesla Cyber Truck<br>Price: RS 9000000</html>");
                      break;
                }
                
                
                if(b[midIndex]==100000000){
                    JOptionPane.showMessageDialog(null,"<html>Name: Semi-Truck<br>Price: RS 100000000</html>");
                      break;
                }
                
                
                if(b[midIndex]==125000000){
                    JOptionPane.showMessageDialog(null,"<html>Name: Lamborgini Huracan<br>Price: RS 125000000</html>");
                      break;
                }
                
                
                if(b[midIndex]==65000000){
                    JOptionPane.showMessageDialog(null,"<html>Name: Lamborgini Countach<br>Price: RS 65000000</html>");
                      break;
                }
                
                if(b[midIndex]==190000000){
                    JOptionPane.showMessageDialog(null,"<html>Name: Lamborgini Avendator<br>Price: RS 190000000</html>");
                      break;
                }
                
                
                if(b[midIndex]==90002000){
                    JOptionPane.showMessageDialog(null,"<html>Name: Lamborgini Urus<br>Price: RS 90002000</html>");
                      break;
                }
                
                if(b[midIndex]==65000060){
                    JOptionPane.showMessageDialog(null,"<html>Name: Audi Q8<br>Price: RS 65000060</html>");
                      break;
                }
                
                if(b[midIndex]==34000030){
                    JOptionPane.showMessageDialog(null,"<html>Name: Audi Q7<br>Price: RS 34000030</html>");
                      break;
                }
                
                if(b[midIndex]==12000000){
                    JOptionPane.showMessageDialog(null,"<html>Name: Audi A6<br>Price: RS 12000000</html>");
                      break;
                }
                
                
                if(b[midIndex]==10000000){
                    JOptionPane.showMessageDialog(null,"<html>Name: Audi A3<br>Price: RS 10000000</html>");
                      break;
                }
                
                if(b[midIndex]==34000000){
                    JOptionPane.showMessageDialog(null,"<html>Name: Tata Q7<br>Price: RS 34000000</html>");
                      break;
                }
                
                if(b[midIndex]==65000020){
                    JOptionPane.showMessageDialog(null,"<html>Name: Tata Q8<br>Price: RS 65000020</html>");
                      break;
                }
                
                
                if(b[midIndex]==15000000){
                    JOptionPane.showMessageDialog(null,"<html>Name: Tata A6<br>Price: RS 15000000</html>");
                      break;
                }
                
                if(b[midIndex]==10100000){
                    JOptionPane.showMessageDialog(null,"<html>Name: Tata A3<br>Price: RS 10100000</html>");
                      break;
                }
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
            }
             
            else if(b[midIndex] < search){
                lowerIndex=midIndex+1;
            }
            else{
                higherIndex=midIndex - 1;
               
                
                
            }
            midIndex=(lowerIndex + higherIndex) / 2;
        }
        if(b[midIndex]!=search){
            JOptionPane.showMessageDialog(null,"<html>Item Not found<br>Enter Another Price</html>");
        }
        
        
            
           
        
    }
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SoftwareDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SoftwareDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SoftwareDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SoftwareDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
      
       
        
     
        
        
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SoftwareDesign().setVisible(true);
            }
            ;
        });
    }
    
    




/*
public int sorting(int sortArray[], int y){
Arrays.sort(sortArray);
sort(sortArray);
System.out.println(Arrays.toString(sortArray));
sort(sortArray);
int start = 0;
int end = sortArray.length -1;

while(start <= end){

int mid = (start+end)/2;

//Checking if the element y is present in th middle of array
if(sortArray[mid] == y){
return sortArray[mid];
}
// checking if y element is greater than right elements from mid element of array and those elements are ignored
else if(y > sortArray[mid]){
start = mid +1;
}
else{
end = mid-1;
}

}
return -1;// returns -1 as the element is not present in the array

}
    
*/
  
    
    /*
    public void sort(int a[]){
        int min,temp=0;
        for(int i=0;i<a.length;i++){
            min=i;
            for(int j=i+1;j<a.length;j++){
                if(a[j]< a[min]){
                    min=j;
                }
            }
            temp=a[i];
            a[i]=a[min];
            a[min]=temp;
        }
        for(int i=0;i<a.length;i++){
            
            System.out.print(a[i]+",");
          
            Integer takeArray=a[i];
        
        }
      
    }

*/
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ModelLabel;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a6;
    private javax.swing.JLabel allendator;
    private javax.swing.JButton audi1;
    private javax.swing.JButton audi2;
    private javax.swing.JButton audi3;
    private javax.swing.JButton audi4;
    private javax.swing.JRadioButton black;
    private javax.swing.JButton bmw1;
    private javax.swing.JButton bmw2;
    private javax.swing.JButton bmw3;
    private javax.swing.JButton bmw4;
    private javax.swing.JButton btnAudi;
    private javax.swing.JButton btnBmw;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnLambo;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTata;
    private javax.swing.JButton btnTesla;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel color;
    private javax.swing.JLabel companyLabel;
    private javax.swing.JLabel companyName;
    private javax.swing.JLabel countach;
    private javax.swing.JLabel cybertruck;
    private javax.swing.JLabel displayPrice;
    private javax.swing.JLabel errorMsg;
    private javax.swing.JLabel fuelType1;
    private javax.swing.JRadioButton grey;
    private javax.swing.JLabel headingText;
    private javax.swing.JLabel hurican;
    private javax.swing.JLabel i8;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton lambo1;
    private javax.swing.JButton lambo2;
    private javax.swing.JButton lambo3;
    private javax.swing.JButton lambo4;
    private javax.swing.JLabel m2;
    private javax.swing.JLabel modelNumber;
    private javax.swing.JLabel price;
    private javax.swing.JLabel pricex1;
    private javax.swing.JPanel propertiesPanel;
    private javax.swing.JLabel q7;
    private javax.swing.JLabel q8;
    private javax.swing.JRadioButton red;
    private javax.swing.JLabel reviewLabel;
    private javax.swing.JLabel s;
    private javax.swing.JComboBox<String> selectFuel;
    private javax.swing.JLabel semiTruck;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JButton tata1;
    private javax.swing.JButton tata2;
    private javax.swing.JButton tata3;
    private javax.swing.JButton tata4;
    private javax.swing.JLabel tataA3;
    private javax.swing.JLabel tataA6;
    private javax.swing.JLabel tataQ7;
    private javax.swing.JLabel tataQ8;
    private javax.swing.JButton tesla1;
    private javax.swing.JButton tesla2;
    private javax.swing.JButton tesla3;
    private javax.swing.JButton tesla4;
    private javax.swing.JLabel urus;
    private javax.swing.JLabel x5;
    private javax.swing.JLabel y;
    private javax.swing.JTextField yourMessage;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
